name: Run checks
on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    env:
      PYTHONPATH: "."
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v2

      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install dependencies"
        run: ./ci/install_deps.sh

      - name: "Test with pytest"
        run: ./ci/run_checks.sh
